title: Personal Blog Site
author: Fauzi Arda
email: fauziardalearning@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is an awesome description to my perfect site

# social links
twitter_username: fauziarda # DO NOT include the @ character, or else the build will fail!
github_username:  fauziardah1 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme : minimal
